use fedlearn_client;
CREATE TABLE IF NOT EXISTS domain_credit_card_fraud_data (
    id bigint unsigned PRIMARY KEY AUTO_INCREMENT,
    batch_id varchar(255) NOT NULL,
    time_step bigint not null,
    V1 double,
    V2 double,
    V3 double,
    V4 double,
    V5 double,
    V6 double,
    V7 double,
    V8 double,
    V9 double,
    V10 double,
    V11 double,
    V12 double,
    V13 double,
    V14 double,
    V15 double,
    V16 double,
    V17 double,
    V18 double,
    V19 double,
    V20 double,
    V21 double,
    V22 double,
    V23 double,
    V24 double,
    V25 double,
    V26 double,
    V27 double,
    V28 double,
    amount double not null,
    class boolean not null
);
