use fedlearn_client;
CREATE TABLE IF NOT EXISTS domain_payment_fraud_data (
    id bigint unsigned PRIMARY KEY AUTO_INCREMENT,
    batch_id varchar(255) NOT NULL,
    FRAUD_FLAG boolean not null,
    PAYMENT_ID varchar(100) not null,
    PAYMENT_INIT_TIMESTAMP double not null,
    PAYMENT_LAST_UPDATE_TIMESTAMP double not null,
    PAYMENT_STATUS varchar(20),
    PAYMENT_TYPE varchar(50),
    DEBITOR_USERNAME varchar(50) not null,
    DEBITOR_FIRST_NAME varchar(50) not null,
    DEBITOR_LAST_NAME varchar(50) not null,
    DEBITOR_EMAIL_ADDRESS varchar(100) not null,
    DEBITOR_PHONE_NUMBER varchar(30) not null,
    DEBITOR_BIRTH_YEAR int not null,
    DEBITOR_BIRTH_MONTH int not null,
    DEBITOR_BIRTH_DAY int not null,
    DEBITOR_GENDER varchar(3) not null,
    DEBITOR_ADDR_BUILDING varchar(20) not null,
    DEBITOR_ADDR_STREET varchar(100) not null,
    DEBITOR_ADDR_CITY varchar(50) not null,
    DEBITOR_ADDR_STATE varchar(50) not null,
    DEBITOR_ADDR_ZIPCODE varchar(20) not null,
    DEBITOR_ADDR_COUNTRY varchar(2) not null,
    DEBITOR_GEO_LATITUDE double not null,
    DEBITOR_GEO_LONGITUDE double not null,
    DEBITOR_ACCOUNT_NUMBER varchar(100) not null,
    DEBITOR_BIC_CODE varchar(50) not null,
    DEBITOR_ACCOUNT_CREATE_TIMESTAMP double not null,
    DEBITOR_CURRENCY varchar(3) not null,
    DEBITOR_IP_ADDRESS varchar(50) not null,
    DEBITOR_TOWER_LATITUDE double not null,
    DEBITOR_TOWER_LONGITUDE double not null,
    DEBITOR_COMMENT varchar(60),
    CREDITOR_USERNAME varchar(50) not null,
    CREDITOR_FIRST_NAME varchar(50) not null,
    CREDITOR_LAST_NAME varchar(50) not null,
    CREDITOR_EMAIL_ADDRESS varchar(100) not null,
    CREDITOR_PHONE_NUMBER varchar(30) not null,
    CREDITOR_BIRTH_YEAR int not null,
    CREDITOR_BIRTH_MONTH int not null,
    CREDITOR_BIRTH_DAY int not null,
    CREDITOR_GENDER varchar(3) not null,
    CREDITOR_ADDR_BUILDING varchar(20) not null,
    CREDITOR_ADDR_STREET varchar(100) not null,
    CREDITOR_ADDR_CITY varchar(50) not null,
    CREDITOR_ADDR_STATE varchar(50) not null,
    CREDITOR_ADDR_ZIPCODE varchar(20) not null,
    CREDITOR_ADDR_COUNTRY varchar(2) not null,
    CREDITOR_GEO_LATITUDE double not null,
    CREDITOR_GEO_LONGITUDE double not null,
    CREDITOR_ACCOUNT_NUMBER varchar(100) not null,
    CREDITOR_BIC_CODE varchar(50) not null,
    CREDITOR_ACCOUNT_CREATE_TIMESTAMP double not null,
    CREDITOR_CURRENCY varchar(3) not null,
    CREDITOR_IP_ADDRESS varchar(50) not null,
    CREDITOR_TOWER_LATITUDE double not null,
    CREDITOR_TOWER_LONGITUDE double not null,
    CREDITOR_COMMENT varchar(60),
    DEBITOR_CCY_CREDITOR_CCY_RATE double not null,
    CREDITOR_CCY_DEBITOR_CCY_RATE double not null,
    DEBITOR_AMOUNT double not null,
    CREDITOR_AMOUNT double not null
);