use fedlearn_client;
INSERT INTO domains (name, label, status)
values (
        'credit_card_fraud',
        'Credit Card',
        'Active'
    );
INSERT INTO model_data_features (
        domain,
        model,
        db_table,
        id_field,
        feature_field,
        seq_num,
        status
    )
values (
        'credit_card_fraud',
        'credit_card_fraud',
        'domain_credit_card_fraud_data',
        'id',
        'v1',
        1,
        'Active'
    ),
    (
        'credit_card_fraud',
        'credit_card_fraud',
        'domain_credit_card_fraud_data',
        'id',
        'v2',
        2,
        'Active'
    ),
    (
        'credit_card_fraud',
        'credit_card_fraud',
        'domain_credit_card_fraud_data',
        'id',
        'v3',
        3,
        'Active'
    ),
    (
        'credit_card_fraud',
        'credit_card_fraud',
        'domain_credit_card_fraud_data',
        'id',
        'v4',
        4,
        'Active'
    ),
    (
        'credit_card_fraud',
        'credit_card_fraud',
        'domain_credit_card_fraud_data',
        'id',
        'v5',
        5,
        'Active'
    ),
    (
        'credit_card_fraud',
        'credit_card_fraud',
        'domain_credit_card_fraud_data',
        'id',
        'v6',
        6,
        'Active'
    ),
    (
        'credit_card_fraud',
        'credit_card_fraud',
        'domain_credit_card_fraud_data',
        'id',
        'v7',
        7,
        'Active'
    ),
    (
        'credit_card_fraud',
        'credit_card_fraud',
        'domain_credit_card_fraud_data',
        'id',
        'v8',
        8,
        'Active'
    ),
    (
        'credit_card_fraud',
        'credit_card_fraud',
        'domain_credit_card_fraud_data',
        'id',
        'v9',
        9,
        'Active'
    ),
    (
        'credit_card_fraud',
        'credit_card_fraud',
        'domain_credit_card_fraud_data',
        'id',
        'v10',
        10,
        'Active'
    ),
    (
        'credit_card_fraud',
        'credit_card_fraud',
        'domain_credit_card_fraud_data',
        'id',
        'v11',
        11,
        'Active'
    ),
    (
        'credit_card_fraud',
        'credit_card_fraud',
        'domain_credit_card_fraud_data',
        'id',
        'v12',
        12,
        'Active'
    ),
    (
        'credit_card_fraud',
        'credit_card_fraud',
        'domain_credit_card_fraud_data',
        'id',
        'v13',
        13,
        'Active'
    ),
    (
        'credit_card_fraud',
        'credit_card_fraud',
        'domain_credit_card_fraud_data',
        'id',
        'v14',
        14,
        'Active'
    ),
    (
        'credit_card_fraud',
        'credit_card_fraud',
        'domain_credit_card_fraud_data',
        'id',
        'v15',
        15,
        'Active'
    ),
    (
        'credit_card_fraud',
        'credit_card_fraud',
        'domain_credit_card_fraud_data',
        'id',
        'v16',
        16,
        'Active'
    ),
    (
        'credit_card_fraud',
        'credit_card_fraud',
        'domain_credit_card_fraud_data',
        'id',
        'v17',
        17,
        'Active'
    ),
    (
        'credit_card_fraud',
        'credit_card_fraud',
        'domain_credit_card_fraud_data',
        'id',
        'v18',
        18,
        'Active'
    ),
    (
        'credit_card_fraud',
        'credit_card_fraud',
        'domain_credit_card_fraud_data',
        'id',
        'v19',
        19,
        'Active'
    ),
    (
        'credit_card_fraud',
        'credit_card_fraud',
        'domain_credit_card_fraud_data',
        'id',
        'v20',
        20,
        'Active'
    ),
    (
        'credit_card_fraud',
        'credit_card_fraud',
        'domain_credit_card_fraud_data',
        'id',
        'v21',
        21,
        'Active'
    ),
    (
        'credit_card_fraud',
        'credit_card_fraud',
        'domain_credit_card_fraud_data',
        'id',
        'v22',
        22,
        'Active'
    ),
    (
        'credit_card_fraud',
        'credit_card_fraud',
        'domain_credit_card_fraud_data',
        'id',
        'v23',
        23,
        'Active'
    ),
    (
        'credit_card_fraud',
        'credit_card_fraud',
        'domain_credit_card_fraud_data',
        'id',
        'v24',
        24,
        'Active'
    ),
    (
        'credit_card_fraud',
        'credit_card_fraud',
        'domain_credit_card_fraud_data',
        'id',
        'v25',
        25,
        'Active'
    ),
    (
        'credit_card_fraud',
        'credit_card_fraud',
        'domain_credit_card_fraud_data',
        'id',
        'v26',
        26,
        'Active'
    ),
    (
        'credit_card_fraud',
        'credit_card_fraud',
        'domain_credit_card_fraud_data',
        'id',
        'v27',
        27,
        'Active'
    ),
    (
        'credit_card_fraud',
        'credit_card_fraud',
        'domain_credit_card_fraud_data',
        'id',
        'v28',
        28,
        'Active'
    ),
    (
        'credit_card_fraud',
        'credit_card_fraud',
        'domain_credit_card_fraud_data',
        'id',
        'amount',
        29,
        'Active'
    );
