use fedlearn_client;
INSERT INTO domains (name, label, status)
values (
        'payment_fraud',
        'Payment',
        'Active'
    );
INSERT INTO model_data_features (
        domain,
        model,
        db_table,
        id_field,
        feature_field,
        seq_num,
        status
    )
values (
        'payment_fraud',
        'payment_fraud',
        'domain_payment_fraud_data',
        'id',
        'DEBITOR_AMOUNT',
        1,
        'Active'
    ),
    (
        'payment_fraud',
        'payment_fraud',
        'domain_payment_fraud_data',
        'id',
        'DEBITOR_GEO_LATITUDE',
        2,
        'Active'
    ),
    (
        'payment_fraud',
        'payment_fraud',
        'domain_payment_fraud_data',
        'id',
        'DEBITOR_GEO_LONGITUDE',
        3,
        'Active'
    ),
    (
        'payment_fraud',
        'payment_fraud',
        'domain_payment_fraud_data',
        'id',
        'DEBITOR_TOWER_LATITUDE',
        4,
        'Active'
    ),
    (
        'payment_fraud',
        'payment_fraud',
        'domain_payment_fraud_data',
        'id',
        'DEBITOR_TOWER_LONGITUDE',
        5,
        'Active'
    ),
    (
        'payment_fraud',
        'payment_fraud',
        'domain_payment_fraud_data',
        'id',
        'CREDITOR_GEO_LATITUDE',
        6,
        'Active'
    ),
    (
        'payment_fraud',
        'payment_fraud',
        'domain_payment_fraud_data',
        'id',
        'CREDITOR_GEO_LONGITUDE',
        7,
        'Active'
    ),
    (
        'payment_fraud',
        'payment_fraud',
        'domain_payment_fraud_data',
        'id',
        'CREDITOR_TOWER_LATITUDE',
        8,
        'Active'
    ),
    (
        'payment_fraud',
        'payment_fraud',
        'domain_payment_fraud_data',
        'id',
        'CREDITOR_TOWER_LONGITUDE',
        9,
        'Active'
    ),
    (
        'payment_fraud',
        'payment_fraud',
        'domain_payment_fraud_data',
        'id',
        'DEBITOR_ACCOUNT_CREATE_TIMESTAMP',
        10,
        'Active'
    ),
    (
        'payment_fraud',
        'payment_fraud',
        'domain_payment_fraud_data',
        'id',
        'CREDITOR_ACCOUNT_CREATE_TIMESTAMP',
        11,
        'Active'
    ),
    (
        'payment_fraud',
        'payment_fraud',
        'domain_payment_fraud_data',
        'id',
        'PAYMENT_INIT_TIMESTAMP',
        12,
        'Active'
    );
