class VendorTypes:
    FLWR = "flwr"
    OTHER = "other"


# flwr strategy types
FLWR_BULYAN = "Bulyan"
FLWR_DIFFERENTIAL_PRIVACY_SERVER_SIDE_ADAPTIVE_CLIPPING = (
    "DifferentialPrivacyServerSideAdaptiveClipping"
)
FLWR_DIFFERENTIAL_PRIVACY_SERVER_SIDE_FIXED_CLIPPING = (
    "DifferentialPrivacyServerSideFixedClipping"
)
FLWR_DP_FED_AVG_ADAPTIVE = "DPFedAvgAdaptive"
FLWR_DP_FED_AVG_FIXED = "DPFedAvgFixed"
FLWR_FAULT_TOLERANT_FED_AVG = "FaultTolerantFedAvg"
FLWR_FED_ADAGRAD = "FedAdagrad"
FLWR_FED_ADAM = "FedAdam"
FLWR_FED_AVG_ANDROID = "FedAvgAndroid"
FLWR_FED_AVG = "FedAvg"
FLWR_FED_AVG_M = "FedAvgM"
FLWR_FED_MEDIAN = "FedMedian"
FLWR_FED_OPT = "FedOpt"
FLWR_FED_PROX = "FedProx"
FLWR_FED_TRIMMED_AVG = "FedTrimmedAvg"
FLWR_FED_XGB_BAGGING = "FedXgbBagging"
FLWR_FED_XGB_CYCLIC = "FedXgbCyclic"
FLWR_FED_XGB_NN_AVG = "FedXgbNnAvg"
FLWR_FED_YOGI = "FedYogi"
FLWR_KRUM = "Krum"
FLWR_Q_FED_AVG = "QFedAvg"

FLWR_STRATEGY_TYPES = [
    FLWR_BULYAN,
    FLWR_DIFFERENTIAL_PRIVACY_SERVER_SIDE_ADAPTIVE_CLIPPING,
    FLWR_DIFFERENTIAL_PRIVACY_SERVER_SIDE_FIXED_CLIPPING,
    FLWR_DP_FED_AVG_ADAPTIVE,
    FLWR_DP_FED_AVG_FIXED,
    FLWR_FAULT_TOLERANT_FED_AVG,
    FLWR_FED_ADAGRAD,
    FLWR_FED_ADAM,
    FLWR_FED_AVG_ANDROID,
    FLWR_FED_AVG,
    FLWR_FED_AVG_M,
    FLWR_FED_MEDIAN,
    FLWR_FED_OPT,
    FLWR_FED_PROX,
    FLWR_FED_TRIMMED_AVG,
    FLWR_FED_XGB_BAGGING,
    FLWR_FED_XGB_CYCLIC,
    FLWR_FED_XGB_NN_AVG,
    FLWR_FED_YOGI,
    FLWR_KRUM,
    FLWR_Q_FED_AVG,
]
FLWR_STRATEGY_TYPES_SUPPORT = [
    FLWR_FED_AVG,
    FLWR_FED_AVG_M,
    FLWR_FED_MEDIAN,
    FLWR_FED_TRIMMED_AVG,
]
# Placeholder for other strategy types
OTHER_STRATEGY_TYPES = []

STRATEGY_TYPES = {
    "flwr": FLWR_STRATEGY_TYPES,
    "other": OTHER_STRATEGY_TYPES,
}
